# Generated by Django 5.2.8 on 2025-12-09 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('desktop_wallpaper_count', models.PositiveIntegerField(default=0)),
                ('mobile_wallpaper_count', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DownloadAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], max_length=10)),
                ('wallpaper_id', models.PositiveIntegerField()),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], help_text="User's device type", max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, help_text='SHA256 hash of IP address for anonymity', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Download Analytics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['wallpaper_type', 'wallpaper_id'], name='wallpapers__wallpap_1cb839_idx'), models.Index(fields=['timestamp'], name='wallpapers__timesta_43f1c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeaturedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], max_length=10)),
                ('wallpaper_id', models.PositiveIntegerField()),
                ('featured_date', models.DateField()),
                ('is_daily_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured_date', 'display_order'],
                'indexes': [models.Index(fields=['featured_date', 'is_daily_featured'], name='wallpapers__feature_3b5120_idx')],
                'unique_together': {('wallpaper_type', 'wallpaper_id', 'featured_date')},
            },
        ),
        migrations.CreateModel(
            name='DesktopWallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('color_palette', models.JSONField(blank=True, default=dict, help_text='JSON: {"primary": "#RRGGBB", "secondary": "#RRGGBB", "accent": "#RRGGBB"}')),
                ('image_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('resolution_width', models.PositiveIntegerField()),
                ('resolution_height', models.PositiveIntegerField()),
                ('aspect_ratio', models.CharField(blank=True, max_length=20)),
                ('file_format', models.CharField(default='JPEG', max_length=10)),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('cdn_path', models.CharField(blank=True, max_length=500)),
                ('quality_label', models.CharField(choices=[('HD', 'HD (720p)'), ('Full HD', 'Full HD (1080p)'), ('2K', '2K (1440p)'), ('4K', '4K (2160p)'), ('8K', '8K (4320p)')], default='HD', max_length=20)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('trending_percentage', models.PositiveSmallIntegerField(default=0, help_text='Random percentage 1-3% when trending')),
                ('is_featured', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_wallpapers', to='wallpapers.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_trending', '-views_count'], name='wallpapers__is_tren_c953ba_idx'), models.Index(fields=['category', '-created_at'], name='wallpapers__categor_b9890e_idx'), models.Index(fields=['-downloads_count'], name='wallpapers__downloa_2f305c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MobileWallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('color_palette', models.JSONField(blank=True, default=dict, help_text='JSON: {"primary": "#RRGGBB", "secondary": "#RRGGBB", "accent": "#RRGGBB"}')),
                ('image_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('resolution_width', models.PositiveIntegerField()),
                ('resolution_height', models.PositiveIntegerField()),
                ('aspect_ratio', models.CharField(blank=True, max_length=20)),
                ('file_format', models.CharField(default='JPEG', max_length=10)),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('cdn_path', models.CharField(blank=True, max_length=500)),
                ('quality_label', models.CharField(choices=[('Phone', 'Phone'), ('Tablet', 'Tablet'), ('HD', 'HD')], default='Phone', max_length=20)),
                ('device_type', models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('both', 'Phone & Tablet')], default='phone', max_length=20)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('trending_percentage', models.PositiveSmallIntegerField(default=0, help_text='Random percentage 1-3% when trending')),
                ('is_featured', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_wallpapers', to='wallpapers.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_trending', '-views_count'], name='wallpapers__is_tren_66f859_idx'), models.Index(fields=['category', '-created_at'], name='wallpapers__categor_0f36f2_idx'), models.Index(fields=['device_type', '-downloads_count'], name='wallpapers__device__6d7671_idx'), models.Index(fields=['-downloads_count'], name='wallpapers__downloa_ef6b0f_idx')],
            },
        ),
    ]
