# Generated by Django 6.0 on 2025-12-24 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0002_remove_desktopwallpaper_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallpaperReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inappropriate', 'Inappropriate content'), ('low_quality', 'Low quality'), ('wrong_category', 'Wrong category'), ('duplicate', 'Duplicate wallpaper'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, help_text='Optional: Your email for follow-up', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='wallpapers.desktopwallpaper')),
            ],
            options={
                'verbose_name': 'Wallpaper Report',
                'verbose_name_plural': 'Wallpaper Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
